name: Build server

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      env: 
           super_secret: ${{ secrets.SuperSecret }}
      run: cd ./server
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
